### ISSUE TITLE
If you open a Shest and hover immediately to an item, it is removed by one

### ISSUE THREAD

**Issue by joaoh1** [vini2003/Shest#7]
It's reproduced more easily with a Wood Shest, and if it's a stack, only 1 of the remaining stack is removed, but if it isn't, it's completely gone.

**Comment by vini2003** [comment]
*what the fuck*

Investigating.

**Comment by vini2003** [comment]
Caused by hovering over the slot while LMB/RMB are held, instantly causing a slot drag, but with an empty cursor stack. Missing sanity checks resulted in it being yeeted out of this plane of existence. Found and fixed, thank you.
